=== usherlabs/logstore-node/packages/core/src/config/config.schema.json
{
	"$id": "config.schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"description": "Node configuration format",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"$schema": {
			"type": "string"
		},
		"logStoreClient": {
			"type": "object",
			"description": "LogStore Client configuration",
			"additionalProperties": true,
			"default": {}
		},
		"streamrClient": {
			"type": "object",
			"description": "Streamr Client configuration",
			"additionalProperties": true,
			"properties": {
				"auth": {
					"anyOf": [
						{
							"type": "object",
							"properties": {
								"privateKey": {
									"type": "string",
									"pattern": "^(0x)?[a-fA-F0-9]{64}$",
									"description": "Private key for authentication, in string format."
								}
							},
							"required": ["privateKey"]
						},
						{
							"type": "object",
							"properties": {
								"ethereum": {
									"type": "object",
									"description": "Ethereum object for Web3 provider-based authentication."
								}
							},
							"required": ["ethereum"]
						}
					]
				}
			},
			"default": {}
		},
		"plugins": {
			"type": "object",
			"description": "Plugin configurations",
			"additionalProperties": true,
			"default": {}
		},
		"mode": {
			"discriminator": {
				"propertyName": "type"
			},
			"type": "object",
			"required": ["type"],
			"oneOf": [
				{
					"type": "object",
					"properties": {
						"type": {
							"type": "string",
							"enum": ["standalone"]
						},
						"topicsStream": {
							"type": "string",
							"description": "Stream ID for validation results from predefined processes."
						},
						"validationErrorsStream": {
							"type": "string",
							"description": "Stream ID for schema validation errors."
						},
						"trackedStreams": {
							"type": "array",
							"description": "Array of objects defining streams to track and the number of partitions they have.",
							"items": {
								"type": "object",
								"properties": {
									"id": {
										"type": "string"
									},
									"partitions": {
										"type": "number"
									}
								},
								"required": ["id", "partitions"]
							}
						}
					},
					"required": ["type", "trackedStreams"]
				},
				{
					"type": "object",
					"properties": {
						"type": {
							"type": "string",
							"enum": ["network"]
						}
					}
				}
			],
			"default": {
				"type": "standalone",
				"trackedStreams": []
			}
		},
		"httpServer": {
			"type": ["object"],
			"description": "HTTP server configuration",
			"default": {},
			"additionalProperties": false,
			"properties": {
				"port": {
					"$ref": "#/definitions/port",
					"description": "Port to start HTTP server on",
					"default": 7171
				},
				"sslCertificate": {
					"description": "Files to use for SSL",
					"type": "object",
					"required": ["certFileName", "privateKeyFileName"],
					"additionalProperties": false,
					"properties": {
						"certFileName": {
							"type": "string",
							"description": "Path of certificate file"
						},
						"privateKeyFileName": {
							"type": "string",
							"description": "Path of private key file"
						}
					}
				}
			}
		}
	},
	"definitions": {
		"port": {
			"type": "number",
			"minimum": 0,
			"maximum": 65353
		},
		"smartContractConfig": {
			"type": "object",
			"required": ["contractAddress", "jsonRpcProvider"],
			"additionalProperties": false,
			"properties": {
				"contractAddress": {
					"type": "string",
					"description": "Ethereum address of registry smart contract",
					"pattern": "^0x[a-fA-F0-9]{40}$"
				},
				"jsonRpcProvider": {
					"type": "string",
					"description": "URL for JSON RPC Provider",
					"format": "uri"
				}
			}
		}
	}
}

=== usherlabs/logstore-node/config-examples/standalone-node-cassandra.example.json
{
	"$schema": "https://schema.streamr.network/config-v2.schema.json",
	"streamrClient": {
		"auth": {
			"privateKey": "0xbb00000000000000000000000000000000000000000000000000000000000001"
		}
	},
	"mode": {
		"type": "standalone",
		"trackedStreams": [
			{
				"id": "0x5e98df807c09a91557d8b3161f2d01852fb005b9/logstore-demo",
				"partitions": 1
			}
		]
	},
	"httpServer": {
		"port": 7774
	},
	"plugins": {
		"logStore": {
			"db": {
				"type": "cassandra",
				"hosts": ["http://127.0.0.1:9042"],
				"username": "",
				"password": "",
				"keyspace": "logstore_1",
				"datacenter": "datacenter1"
			},
			"programs": {
				"chainRpcUrls": {
					"137": "https://polygon.llamarpc.com"
				}
			}
		}
	}
}

=== usherlabs/logstore-node/config-examples/standalone-node.example.json
{
	"$schema": "https://schema.streamr.network/config-v2.schema.json",
	"streamrClient": {
		"auth": {
			"privateKey": "0xbb00000000000000000000000000000000000000000000000000000000000001"
		}
	},
	"mode": {
		"type": "standalone",
		"trackedStreams": [
			{
				"id": "0xd37dc4d7e2c1bdf3edd89db0e505394ea69af43d/gas-station/ethereum",
				"partitions": 1
			}
		]
	},
	"httpServer": {
		"port": 7774
	},
	"plugins": {
		"logStore": {
			"db": {
				"type": "sqlite",
				"dataPath": ".logstore/data/logstore-node.db"
			},
			"programs": {
				"chainRpcUrls": {
					"137": "https://polygon.llamarpc.com"
				}
			}
		}
	}
}

=== usherlabs/logstore-node/packages/core/configs/development-standalone-1.env.json
{
	"$schema": "https://schema.streamr.network/config-v2.schema.json",
	"logStoreClient": {
		"contracts": {
			"logStoreNodeManagerChainAddress": "0x85ac4C8E780eae81Dd538053D596E382495f7Db9",
			"logStoreStoreManagerChainAddress": "0x8560200b8E7477FB09281A0566B50fa6E7a66a34",
			"logStoreQueryManagerChainAddress": "0x65d379f29BE436bD367699f3Dd7A436c54795a49",
			"logStoreTheGraphUrl": "http://127.0.0.1:8000/subgraphs/name/logstore-dev/network-contracts"
		}
	},
	"streamrClient": {
		"logLevel": "trace",
		"auth": {
			"privateKey": "0xbb00000000000000000000000000000000000000000000000000000000000004"
		},
		"network": {
			"id": "0x392Bd2cb87f5670F321Ad521397d30a00c582b34",
			"trackers": [
				{
					"id": "0xb9e7cEBF7b03AE26458E32a059488386b05798e8",
					"ws": "ws://127.0.0.1:30301",
					"http": "http://127.0.0.1:30301"
				},
				{
					"id": "0x0540A3e144cdD81F402e7772C76a5808B71d2d30",
					"ws": "ws://127.0.0.1:30302",
					"http": "http://127.0.0.1:30302"
				},
				{
					"id": "0xf2C195bE194a2C91e93Eacb1d6d55a00552a85E2",
					"ws": "ws://127.0.0.1:30303",
					"http": "http://127.0.0.1:30303"
				}
			],
			"location": {
				"latitude": 60.19,
				"longitude": 24.95,
				"country": "Finland",
				"city": "Helsinki"
			},
			"webrtcDisallowPrivateAddresses": false
		},
		"contracts": {
			"streamRegistryChainAddress": "0x6cCdd5d866ea766f6DF5965aA98DeCCD629ff222",
			"streamStorageRegistryChainAddress": "0xd04af489677001444280366Dd0885B03dAaDe71D",
			"storageNodeRegistryChainAddress": "0x231b810D98702782963472e1D60a25496999E75D",
			"streamRegistryChainRPCs": {
				"chainId": 8997,
				"rpcs": [
					{
						"url": "http://127.0.0.1:8546"
					}
				]
			},
			"mainChainRPCs": {
				"chainId": 8995,
				"rpcs": [
					{
						"url": "http://127.0.0.1:8545"
					}
				]
			},
			"theGraphUrl": "http://127.0.0.1:8000/subgraphs/name/streamr-dev/network-contracts"
		},
		"metrics": false
	},
	"mode": {
		"type": "standalone",
		"trackedStreams": [
			{
				"id": "0x392bd2cb87f5670f321ad521397d30a00c582b34/mpctlsproofspublic",
				"partitions": 1
			}
		]
	},
	"httpServer": {
		"port": 7774
	},
	"plugins": {
		"logStore": {
			"db": {
				"type": "sqlite"
			},
			"logStoreConfig": {
				"refreshInterval": 10000
			},
			"programs": {
				"chainRpcUrls": {
					"8997": "http://127.0.0.1:8546"
				}
			}
		}
	}
}
